# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: lzn12345
  freemarker:
    cache: false
    suffix: .ftl
mybatis-plus:
  mapper-locations: classpath*:/nu/**Mapper.xml
