spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiangmu?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: lzn12345

mybatis-plus:
  type-alises-package: org.lanqiao.pojo
  configurtion:
    map-underscore-to-caml-casmel-case: true

thymeleaf:
  cache: false # 不要缓存 修改了模板自动生效
  check-template-location: 'true' # 检查模板的位置
  mode: HTML5
  prefix: 'classpath:/templates/'  # 模板的位置
  suffix: '.html'    # 模板的后缀
  servlet:
    content-type: 'text/html '
  encoding: UTF-8

#server:
#  port: 8080
#  servlet:
#    context-path: //yyds